### ISSUE TITLE
Poor highlight text visibility in thunar

### ISSUE THREAD

**Issue by Dejweed** [donfaustinocortizone/Nashville96#2]
Hello!

- I'm using Nashville Solarized. Selecting a file in thunar makes the text hard to see. Take a look:
![image](https://github.com/donfaustinocortizone/Nashville96/assets/65261588/f4e388a7-bcdc-4757-8cad-a9a5c3ff4e5c)

- Xfwm theme close button of maximized windows isn't clicked when moving the mouse to the top right corner. With Chicago95 I can just click the top right corner of the screen and close the window. I miss this behavior here.

- CSD buttons could also be recolored, now they are gray and look out of place:
![image](https://github.com/donfaustinocortizone/Nashville96/assets/65261588/81d5cbe2-8dfa-446b-a0ca-51e5b76972ae)

Nice theme btw! Have you considered contributing to Chicago95? Your work would benefit upstream greatly. I would love to see Chicago95 come with dark theme for gtk3 by default. 
I would also like gtk themes to have better HiDPI support (for example non-blurry scrollbar arrows at 2x scale). 

Thank you for your work.

**Comment by donfaustinocortizone** [comment]
Hello.

Sorry for the delay, i updated the repo to reflect the fixes to the problems depicted here. Let me know if you're still presenting any issue.

**Comment by Dejweed** [comment]
Nice work and thank you!

Some new issues I found:

- The same highlighting issue is also present in nemo.

- Switching to dark mode on gnome makes some programs (in my case gnome-tweaks and simple-scan) fallback to adwaita theme. Linking gtk-dark.css to gtk.css in gtk-3.0 fixes this for me.

https://github.com/donfaustinocortizone/Nashville96/assets/65261588/726a186a-cfb7-4a32-97f9-5b8041a2fa77

- Document scanner (simple-scan) is messed up (missing borders, preferences menu doesn't have a close button). This is also an issue in Chicago95.
- The titlebar (where the blue would be in Chicago95) is just a single line at the top. Is this intentional?
- Some symbolic icons are black (not an issue in Nashville96-Steam). They are white with Adwaita icon theme. I'm using SE98, but I don't think this is an icon theme issue.
![Screenshot from 2024-01-04 21-12-20](https://github.com/donfaustinocortizone/Nashville96/assets/65261588/9501f8a1-48d1-4310-9124-3cd067c7f713)
- Pressed CSD buttons are too similar to non normal ones (not an issue in Nashville96-Steam)

Now one minor thing, I think it would be better to have xfwm themes borderless by default and bordered as an option (to match gtk).

Would you also be interested in adding the light colors? This way they would be just normal themes, respecting system's light/dark preferences? I understand that this is beyond this project's intention, but it would be cool to have a complete modern gtk theme.

**Comment by donfaustinocortizone** [comment]
Hello, i'm back again.

> * The same highlighting issue is also present in nemo.

Fixed.

> * Switching to dark mode on gnome makes some programs (in my case gnome-tweaks and simple-scan) fallback to adwaita theme. Linking gtk-dark.css to gtk.css in gtk-3.0 fixes this for me.

I linked gtk-dark by default now.




> * Document scanner (simple-scan) is messed up (missing borders, preferences menu doesn't have a close button). This is also an issue in Chicago95.

This was somewhat tricky to fix. I increased titlebar heights, so they shouldn't shrink in menus anymore, however i couldn't find a way to add borders. 
![capture1](https://github.com/donfaustinocortizone/Nashville96/assets/116418730/198b2b6d-1124-48d4-9916-84b3f7213726)



> * The titlebar (where the blue would be in Chicago95) is just a single line at the top. Is this intentional?

No, it isn't. I don't have this issue in my setup, could be caused by a different version of GTK or XFWM?
![capture2](https://github.com/donfaustinocortizone/Nashville96/assets/116418730/dc78f2bf-3be4-48ce-b2da-4917fa7adc3a)



> * Some symbolic icons are black (not an issue in Nashville96-Steam). They are white with Adwaita icon theme. I'm using SE98, but I don't think this is an icon theme issue.

Icons for the treeview should be displayed with the correct light colors now. However, the close icon in tabs for some explorers such as Thunar and Caja still show black, i think this may be related to the icon theme (as i tested with other dark themes and they show like that). Nemo should alright though.

> * Pressed CSD buttons are too similar to non normal ones (not an issue in Nashville96-Steam)

Fixed, they should behave like normal WM buttons now.

> Now one minor thing, I think it would be better to have xfwm themes borderless by default and bordered as an option (to match gtk).

I added bordered themes by default because they would be more suitable for visibility between many windows. But yes, i consider shipping the borderless themes as default as that would help with consistency (specially with CSD apps). 



> Would you also be interested in adding the light colors? This way they would be just normal themes, respecting system's light/dark preferences? I understand that this is beyond this project's intention, but it would be cool to have a complete modern gtk theme.

I would like to (in fact, i have some colorschemes for the light versions). Unfortunately, i'm very busy with personal stuff so i'll be focusing only in bug-fixing for this project for now.

**Comment by Dejweed** [comment]
Awesome! Thank you so much.

> However, the close icon in tabs for some explorers such as Thunar and Caja still show black

That's because they aren't symbolic icons, so this is a thunar issue.

> The titlebar (where the blue would be in Chicago95) is just a single line at the top.

I see this line in CSD programs when not maximized.

- Also, I'm seeing some transparent areas in Lutris when maximized (under the headerbar), also in thunar's "close window with multiple tabs?" warning. And you forgot the restore buttons (now they are the same as minimize)
![image](https://github.com/donfaustinocortizone/Nashville96/assets/65261588/6eb7bc39-22e7-4e21-bda3-2bb054daf91b)

**Comment by donfaustinocortizone** [comment]
> I see this line in CSD programs when not maximized.

Oh, i see the issue now. I'll consider this intentional as part of the headerbar for now.



> * Also, I'm seeing some transparent areas in Lutris when maximized (under the headerbar), also in thunar's "close window with multiple tabs?" warning. And you forgot the restore buttons (now they are the same as minimize)

It should be fixed by now, it was caused by the margin at the bottom. Also corrected the restore buttons.

Let me know if you still have any issue.

**Comment by Dejweed** [comment]
Nice! That would be it for now. I don't see any issues with your theme specifically. There is [this one](https://github.com/grassmunk/Chicago95/issues/326) inherited from Chicago95 that could be improved. In Windows 98 the selected item has a dotted border, which is missing in Chicago95. Looking at Adwaita, Thunar only uses this highlight on detailed view, while Nemo has it in all views. Here's a screenshot from Win98 (notice fonts folder):

![image](https://github.com/donfaustinocortizone/Nashville96/assets/65261588/70298cce-0c94-429e-a4a5-6cbf6c428748)

**Comment by Dejweed** [comment]
Just did some testing in cinnamon. The gtk theme thumbnails should be updated. Window manager issues (not steam version): 

- titlebar buttons are blurry

- there's a small semi transparent shadow

- inactive titlebars are lighter color.

Let me know if I should make new seperate issues in the future, to make things more organised. And thank you for your work :)

**Comment by donfaustinocortizone** [comment]
Hello! Thanks for the report and sorry for the delayed response.
I'm going to archive Nashville96 soon, so I won't be able to provide support going forward (I no longer use Linux). I'll close this issue for archival purposes.
If this is still affecting you, I’d recommend addressing it in a fork.
